---
matlab_version: R2021b
matlab_iso_dir: /data/volume_2
matlab_iso_file: "{{ matlab_version }}_Linux.iso"
matlab_configfile_file: matlab_config.yml
matlab_configfile_path: "{{ matlab_iso_dir }}/{{ matlab_configfile_file }}"
matlab_license_dir: /root
matlab_dir: /usr/local/MATLAB

# below variable content is placeholder, should be overwritten dynamically 
# using the file referred to by "matlab_configfile_path"
matlab_file_installation_key: replace-this-text-by-your-own-key
matlab_license_text: "replace-this-text-with-content\nfor-license.dat-file"

# matlab_products is a list of the products that should be installed 
matlab_products:
  - product.5G_Toolbox
  - product.AUTOSAR_Blockset
  - product.Aerospace_Blockset
  - product.Aerospace_Toolbox
  - product.Antenna_Toolbox
  - product.Audio_Toolbox
  - product.Automated_Driving_Toolbox
  - product.Bioinformatics_Toolbox
  - product.Communications_Toolbox
  - product.Computer_Vision_Toolbox
  - product.Control_System_Toolbox
  - product.Curve_Fitting_Toolbox
  - product.DDS_Blockset
  - product.DO_Qualification_Kit
  - product.DSP_System_Toolbox
  - product.Data_Acquisition_Toolbox
  - product.Database_Toolbox
  - product.Datafeed_Toolbox
  - product.Deep_Learning_HDL_Toolbox
  - product.Deep_Learning_Toolbox
  - product.Econometrics_Toolbox
  - product.Embedded_Coder
  - product.Filter_Design_HDL_Coder
  - product.Financial_Instruments_Toolbox
  - product.Financial_Toolbox
  - product.Fixed-Point_Designer
  - product.Fuzzy_Logic_Toolbox
  - product.GPU_Coder
  - product.Global_Optimization_Toolbox
  - product.HDL_Coder
  - product.HDL_Verifier
  - product.IEC_Certification_Kit
  - product.Image_Acquisition_Toolbox
  - product.Image_Processing_Toolbox
  - product.Instrument_Control_Toolbox
  - product.LTE_Toolbox
  - product.Lidar_Toolbox
  - product.MATLAB
  - product.MATLAB_Coder
  - product.MATLAB_Compiler
  - product.MATLAB_Compiler_SDK
  - product.MATLAB_Parallel_Server
  - product.MATLAB_Production_Server
  - product.MATLAB_Report_Generator
  - product.MATLAB_Web_App_Server
  - product.Mapping_Toolbox
  - product.Mixed-Signal_Blockset
  - product.Model_Predictive_Control_Toolbox
  - product.Model-Based_Calibration_Toolbox
  - product.Motor_Control_Blockset
  - product.Navigation_Toolbox
  - product.OPC_Toolbox
  - product.Optimization_Toolbox
  - product.Parallel_Computing_Toolbox
  - product.Partial_Differential_Equation_Toolbox
  - product.Phased_Array_System_Toolbox
  - product.Polyspace_Bug_Finder
  - product.Polyspace_Bug_Finder_Server
  - product.Polyspace_Code_Prover
  - product.Polyspace_Code_Prover_Server
  - product.Powertrain_Blockset
  - product.Predictive_Maintenance_Toolbox
  - product.RF_Blockset
  - product.RF_PCB_Toolbox
  - product.RF_Toolbox
  - product.ROS_Toolbox
  - product.Radar_Toolbox
  - product.Reinforcement_Learning_Toolbox
  - product.Risk_Management_Toolbox
  - product.Robotics_System_Toolbox
  - product.Robust_Control_Toolbox
  - product.Satellite_Communications_Toolbox
  - product.Sensor_Fusion_and_Tracking_Toolbox
  - product.SerDes_Toolbox
  - product.Signal_Integrity_Toolbox
  - product.Signal_Processing_Toolbox
  - product.SimBiology
  - product.SimEvents
  - product.Simscape
  - product.Simscape_Driveline
  - product.Simscape_Electrical
  - product.Simscape_Fluids
  - product.Simscape_Multibody
  - product.Simulink
  - product.Simulink_3D_Animation
  - product.Simulink_Check
  - product.Simulink_Code_Inspector
  - product.Simulink_Coder
  - product.Simulink_Compiler
  - product.Simulink_Control_Design
  - product.Simulink_Coverage
  - product.Simulink_Design_Optimization
  - product.Simulink_Design_Verifier
  - product.Simulink_Desktop_Real-Time
  - product.Simulink_PLC_Coder
  - product.Simulink_Real-Time
  - product.Simulink_Report_Generator
  - product.Simulink_Requirements
  - product.Simulink_Test
  - product.SoC_Blockset
  - product.Spreadsheet_Link
  - product.Stateflow
  - product.Statistics_and_Machine_Learning_Toolbox
  - product.Symbolic_Math_Toolbox
  - product.System_Composer
  - product.System_Identification_Toolbox
  - product.Text_Analytics_Toolbox
  - product.UAV_Toolbox
  - product.Vehicle_Dynamics_Blockset
  - product.Vehicle_Network_Toolbox
  - product.Vision_HDL_Toolbox
  - product.WLAN_Toolbox
  - product.Wavelet_Toolbox
  - product.Wireless_HDL_Toolbox
