---
# Note that below config of uwsgi depends on 
# nginx (plugin) already installed and configured using SURF config parameters
# 
#
- name: ensure uwsgi service is installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "uwsgi"
    - "uwsgi-plugin-python3"

- name: configure uwsgi within nginx for locations starting with '/w'
  copy:
    src: "nginx-uwsgi.conf"
    dest: "/etc/nginx/app-location-conf.d/uwsgi.conf"
    mode: 0644

- name: copy example uwsgi.ini file to /etc/uwsgi/apps-available
  copy:
    src: "uwsgi-example.ini"
    dest: "/etc/uwsgi/apps-available/example.ini"
    mode: 0644    


- name: start uwsgi service at boot
  service:
    name: uwsgi
    state: started
    enabled: yes
