---
- name: ensure java runtime is installed
  package:
    name: "default-jre"
    state: present

- name: download camunda modeler
  get_url:
    url: "{{ camunda_modeler_urldir }}/{{ camunda_modeler_urlfile_prefix }}.tar.gz"
    dest: "/tmp/{{ camunda_modeler_urlfile_prefix }}.tar.gz"

- name: unpack modeler tar.gz file in tmp location
  unarchive:
    src: "/tmp/{{ camunda_modeler_urlfile_prefix }}.tar.gz"
    dest: "/tmp/{{ camunda_modeler_urlfile_prefix }}"

- name: make sure camunda-modeler target dir does not yet exist
  file:
    dest: "{{ camunda_modeler_dir }}"
    state: absent

- name: move unpacked modeler directory content to /var/lib
  command: mv "/tmp/{{ camunda_modeler_urlfile_prefix }}" "{{ camunda_modeler_dir }}"
  
- name: add link to Camunda modeler executable in /usr/bin
  file:
    src: "{{ camunda_modeler_dir }}/camunda-modeler"
    dest: "/usr/bin/camunda-modeler"
    state: link

- name: add desktop menu entry and mime-type binding for Camunda modeler
  shell: "{{ camunda_modeler_dir }}/support/xdg_register.sh"

 
