---

- name: create target directory for guisync files
  file:
    dest: "{{ irods_guisync_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: copy irods_guisync files to target dir
  copy:
    src: "{{ item }}"
    dest: "{{ irods_guisync_dir }}/{{ item }}"
    mode: 0755
  with_items:
    - "guisync.py"
    - "guisync.css"
    - "UU_logo_2021_EN_RGB_transparant.png"
    - "MainWindow.py"
    - "LogWindow.py"
    - "IrodsStore.py"
    - "IrodsChooserDialog.py"

- name: install desktop launcher for irods_guisync
  include: desktop.yml
