---
- name: install package sshfs
  package:
    name: sshfs
    state: present

- name: ensure that local mountpoint exists
  file:
    path: "{{ sshfs_mountpoint }}"
    state: directory
    owner: "{{ robotuser_name }}"

- name: enable user_allow_other in fuse config
  lineinfile:
    path: /etc/fuse.conf
    regexp: '^#user_allow_other$'
    line: 'user_allow_other'
    state: present

# below is a hack to split the task of mounting the remote filesystem
# in two parts so that privileged part of update /etc/fstab is done by root
# Note that to make this work, only the 'state' differs  
- name: add remote filesystem to /etc/fstab
  mount:
    src: "sshfs#{{ robotuser_name }}@{{ sshfs_server }}:{{ sshfs_sourcepath }}"
    path: "{{ sshfs_mountpoint }}"
    fstype: "fuse"
    opts: "_netdev,user,idmap=user,allow_other,default_permissions,reconnect,ServerAliveInterval=20,ServerAliveCountMax=5"
    state: present

- name: mount remote filesystem using credentials of robot user
  become: true
  become_user: "{{ robotuser_name }}"
  mount:
    src: "sshfs#{{ robotuser_name }}@{{ sshfs_server }}:{{ sshfs_sourcepath }}"
    path: "{{ sshfs_mountpoint }}"
    fstype: "fuse"
    opts: "_netdev,user,idmap=user,allow_other,default_permissions,reconnect,ServerAliveInterval=20,ServerAliveCountMax=5"
    state: mounted



