---
jupyterhub_port: 8000
jupyterhub_config_dir: /usr/local/etc/jupyter/
jupyterhub_uri: /
jupyterhub_auth: sram
jupyterhub_bind_addr: 127.0.0.1
jupyterhub_extra_pkgs: []
jupyterhub_config_extra: ""
jupyterhub_allowed_users_group: jupyterhub
jupyterhub_enable_notebooks: true
jupyterhub_proxy_config: {}
jupyterhub_http_username: ""
jupyterhub_http_password: ""
jupyterhub_create_default_group: true
jupyterhub_remote_user_header: REMOTE_USER
jupyterhub_activate_remote_user_auth: false
jupyterhub_enable_unix_socket: true
jupyterhub_config_env_keep:
  - JUPYTERHUB_ACTIVITY_URL
  - JUPYTERHUB_SERVER_NAME
  - JUPYTERHUB_API_URL
  - JUPYTERHUB_API_TOKEN
  - JUPYTERHUB_SERVICE_URL
  - JUPYTERHUB_SINGLEUSER_APP
  - JUPYTERHUB_USER
  - JUPYTERHUB_GROUP
  - PYTHONPATH
  - PATH
  - CONDA_ROOT
  - CONDA_DEFAULT_ENV
