---
galaxy_info:
  author: Dawa Ometto
  description: Install tigervnc server
  license: GPLv3
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
