---

galaxy_info:
  author: Ton Smeele
  description: obtain a data structure with a list of regular Linux users
  license: GPLv3
  min_ansible_version: '2.6'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all
