---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Test rstudio
      ansible.builtin.uri:
        url: http://localhost/hub/spawn/testuser?next=%2Fhub%2Fuser%2Ftestuser%2Frstudio%2F
        method: GET
        headers:
          user: testuser # mock SRAM login
        return_content: true
        follow_redirects: true
      register: rstudio_login
      retries: 5
      delay: 3

    - name: Assert content correct
      ansible.builtin.assert:
        that:
          - '"Posit" in rstudio_login.content'
