---
# adds iRODS repository, method depends on distro

- name: enable iRODS repository, yum package manager
  yum_repository:
    name: iRODS
    description: RENCI iRODS Repository
    baseurl: https://packages.irods.org/yum/pool/centos{{ansible_distribution_major_version}}/{{ansible_architecture}}
    gpgkey: https://packages.irods.org/irods-signing-key.asc
    gpgcheck: yes
  when: ansible_pkg_mgr  == 'yum'

- name: run apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_pkg_mgr == 'apt'

- name: add iRODS repository apt-key
  apt_key:
    url: https://packages.irods.org/irods-signing-key.asc
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: add iRODS repository for apt package manager
  apt_repository:
    repo: 'deb https://packages.irods.org/apt/ {{ansible_distribution_release}} main'
    state: present
    filename: renci-irods
    update_cache: yes
  when: ansible_pkg_mgr  == 'apt'
