---
galaxy_info:
  author: Dawa Ometto
  description: Install an app as a JupyterHub Server extensions.
  license: GPLv3
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all # not tested for specific versions
dependencies:
  - role: system_python
